import Head from 'next/head';
import React from 'react';

import { Container, Main, Section } from './style';
import Quizzizlist from '@/src/components/Quizzizlist';

const generateCardsData = (count: number) => {
    const cards = [];
    for (let i = 1; i <= count; i++) {
        cards.push({ title: `Card ${i}`, description: `Descrição do Card ${i}` });
    }
    return cards;
};

const cardsData = generateCardsData(32);

const Home: React.FC = () => {
    return (
        <div>
            <Section></Section>
            <Container>
                <Head>
                    <title>My Cards App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Main>
                    <Quizzizlist cards={cardsData} />
                </Main>
            </Container>
        </div>
    );
};

export default Home;